package com.finance.mapper.perms;

import com.finance.pojo.perms.AdminPermsView;
import com.finance.pojo.perms.AdminPermsViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminPermsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    long countByExample(AdminPermsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    int deleteByExample(AdminPermsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    int insert(AdminPermsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    int insertSelective(AdminPermsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    List<AdminPermsView> selectByExample(AdminPermsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminPermsView record, @Param("example") AdminPermsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms_view
     *
     * @mbg.generated Thu Jul 16 18:32:04 CST 2020
     */
    int updateByExample(@Param("record") AdminPermsView record, @Param("example") AdminPermsViewExample example);
}