package com.finance.mapper.others;

import com.finance.pojo.others.ChangeMoney;
import com.finance.pojo.others.ChangeMoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChangeMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int countByExample(ChangeMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int deleteByExample(ChangeMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int insert(ChangeMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int insertSelective(ChangeMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    List<ChangeMoney> selectByExample(ChangeMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    ChangeMoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChangeMoney record, @Param("example") ChangeMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByExample(@Param("record") ChangeMoney record, @Param("example") ChangeMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByPrimaryKeySelective(ChangeMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByPrimaryKey(ChangeMoney record);
}