package com.finance.mapper.others;

import com.finance.pojo.others.FundProduct;
import com.finance.pojo.others.FundProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int countByExample(FundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int deleteByExample(FundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int insert(FundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int insertSelective(FundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    List<FundProduct> selectByExample(FundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    FundProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") FundProduct record, @Param("example") FundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByExample(@Param("record") FundProduct record, @Param("example") FundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByPrimaryKeySelective(FundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByPrimaryKey(FundProduct record);
}