package com.finance.mapper.others;

import com.finance.pojo.others.Permissions;
import com.finance.pojo.others.PermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int countByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int deleteByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    List<Permissions> selectByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    Permissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Permissions record, @Param("example") PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByExample(@Param("record") Permissions record, @Param("example") PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    int updateByPrimaryKey(Permissions record);
}