package com.finance.mapper.others;

import com.finance.pojo.others.TermFinancial;
import com.finance.pojo.others.TermFinancialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TermFinancialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int countByExample(TermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int deleteByExample(TermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int insert(TermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int insertSelective(TermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    List<TermFinancial> selectByExample(TermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    TermFinancial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TermFinancial record, @Param("example") TermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByExample(@Param("record") TermFinancial record, @Param("example") TermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByPrimaryKeySelective(TermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_financial
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    int updateByPrimaryKey(TermFinancial record);
}