package com.finance.pojo.others;

public class Bankcard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.cardBank
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String cardbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.cardNum
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.userId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.id
     *
     * @return the value of bankcard.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.id
     *
     * @param id the value for bankcard.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.cardBank
     *
     * @return the value of bankcard.cardBank
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getCardbank() {
        return cardbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.cardBank
     *
     * @param cardbank the value for bankcard.cardBank
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setCardbank(String cardbank) {
        this.cardbank = cardbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.type
     *
     * @return the value of bankcard.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.type
     *
     * @param type the value for bankcard.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.cardNum
     *
     * @return the value of bankcard.cardNum
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.cardNum
     *
     * @param cardnum the value for bankcard.cardNum
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.userId
     *
     * @return the value of bankcard.userId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.userId
     *
     * @param userid the value for bankcard.userId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}