package com.finance.pojo.others;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.name
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.assets
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bankDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String bankdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.id
     *
     * @return the value of bank.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.id
     *
     * @param id the value for bank.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.name
     *
     * @return the value of bank.name
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.name
     *
     * @param name the value for bank.name
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.type
     *
     * @return the value of bank.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.type
     *
     * @param type the value for bank.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.assets
     *
     * @return the value of bank.assets
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getAssets() {
        return assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.assets
     *
     * @param assets the value for bank.assets
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setAssets(String assets) {
        this.assets = assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bankDesc
     *
     * @return the value of bank.bankDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getBankdesc() {
        return bankdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bankDesc
     *
     * @param bankdesc the value for bank.bankDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setBankdesc(String bankdesc) {
        this.bankdesc = bankdesc;
    }
}