package com.finance.pojo.others;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.assets
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.bankDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String bankDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.id
     *
     * @return the value of bank.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.id
     *
     * @param id the value for bank.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.name
     *
     * @return the value of bank.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.name
     *
     * @param name the value for bank.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.type
     *
     * @return the value of bank.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.type
     *
     * @param type the value for bank.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.assets
     *
     * @return the value of bank.assets
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getAssets() {
        return assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.assets
     *
     * @param assets the value for bank.assets
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAssets(String assets) {
        this.assets = assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.bankDesc
     *
     * @return the value of bank.bankDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getBankDesc() {
        return bankDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.bankDesc
     *
     * @param bankDesc the value for bank.bankDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setBankDesc(String bankDesc) {
        this.bankDesc = bankDesc;
    }
}