package com.finance.pojo.others;

import com.finance.pojo.user.User;

public class Bankcard {
    User user;

    @Override
    public String toString() {
        return "Bankcard{" +
                "user=" + user +
                ", id=" + id +
                ", cardBank='" + cardBank + '\'' +
                ", type=" + type +
                ", cardNum='" + cardNum + '\'' +
                ", userId=" + userId +
                '}';
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.cardBank
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String cardBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.cardNum
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.id
     *
     * @return the value of bankcard.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.id
     *
     * @param id the value for bankcard.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.cardBank
     *
     * @return the value of bankcard.cardBank
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getCardBank() {
        return cardBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.cardBank
     *
     * @param cardBank the value for bankcard.cardBank
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCardBank(String cardBank) {
        this.cardBank = cardBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.type
     *
     * @return the value of bankcard.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.type
     *
     * @param type the value for bankcard.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.cardNum
     *
     * @return the value of bankcard.cardNum
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.cardNum
     *
     * @param cardNum the value for bankcard.cardNum
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.userId
     *
     * @return the value of bankcard.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.userId
     *
     * @param userId the value for bankcard.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}