package com.finance.pojo.others;

import java.math.BigDecimal;

public class ChangeMoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal annualIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.peiIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal peiIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String invesTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_money.invesMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal invesMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.id
     *
     * @return the value of change_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.id
     *
     * @param id the value for change_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.name
     *
     * @return the value of change_money.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.name
     *
     * @param name the value for change_money.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.annualIncome
     *
     * @return the value of change_money.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getAnnualIncome() {
        return annualIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.annualIncome
     *
     * @param annualIncome the value for change_money.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAnnualIncome(BigDecimal annualIncome) {
        this.annualIncome = annualIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.peiIncome
     *
     * @return the value of change_money.peiIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getPeiIncome() {
        return peiIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.peiIncome
     *
     * @param peiIncome the value for change_money.peiIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setPeiIncome(BigDecimal peiIncome) {
        this.peiIncome = peiIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.invesTerm
     *
     * @return the value of change_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getInvesTerm() {
        return invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.invesTerm
     *
     * @param invesTerm the value for change_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInvesTerm(String invesTerm) {
        this.invesTerm = invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_money.invesMoney
     *
     * @return the value of change_money.invesMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getInvesMoney() {
        return invesMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_money.invesMoney
     *
     * @param invesMoney the value for change_money.invesMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInvesMoney(BigDecimal invesMoney) {
        this.invesMoney = invesMoney;
    }
}