package com.finance.pojo.others;

import com.finance.pojo.user.User;

import java.math.BigDecimal;
import java.util.Date;

public class FlowOfFunds {


    public static class Builder {
        private User user;

        public Builder user(User user) {
            this.user = user;
            return this;
        }

        private Integer id;

        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        private Integer userId;

        public Builder userId(Integer userId) {
            this.userId = userId;
            return this;
        }

        private BigDecimal flowMoney;

        public Builder flowMoney(BigDecimal flowMoney) {
            this.flowMoney = flowMoney;
            return this;
        }

        private Integer type;

        public Builder type(Integer type) {
            this.type = type;
            return this;
        }

        private String source;

        public Builder source(String source) {
            this.source = source;
            return this;
        }

        private Date createTime;

        public Builder createTime(Date createTime) {
            this.createTime = createTime;
            return this;
        }

        private String fundDesc;

        public Builder fundDesc(String fundDesc) {
            this.fundDesc = fundDesc;
            return this;
        }

        public Builder() {
        }

        public FlowOfFunds build() {
            return new FlowOfFunds(this);
        }

    }

    private static final Integer flowIn = 2;
    private static final Integer flowOut = 1;

    public static Integer flowIn() {
        return flowIn;
    }

    public static Integer flowOut() {
        return flowOut;
    }

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public FlowOfFunds() {
    }

    private FlowOfFunds(Builder builder) {
        this.id = builder.id;
        this.userId = builder.userId;
        this.flowMoney = builder.flowMoney;
        this.type = builder.type;
        this.source = builder.source;
        this.createTime = builder.createTime;
        this.fundDesc = builder.fundDesc;
    }

    @Override
    public String toString() {
        return "FlowOfFunds{" +
                "user=" + user +
                ", id=" + id +
                ", userId=" + userId +
                ", flowMoney=" + flowMoney +
                ", type=" + type +
                ", source='" + source + '\'' +
                ", createTime=" + createTime +
                ", fundDesc='" + fundDesc + '\'' +
                '}';
    }

    public FlowOfFunds(Integer id, Integer userId, BigDecimal flowMoney,
                       Integer type, String source, Date createTime, String fundDesc) {
        this.id = id;
        this.userId = userId;
        this.flowMoney = flowMoney;
        this.type = type;
        this.source = source;
        this.createTime = createTime;
        this.fundDesc = fundDesc;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.flowMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal flowMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.source
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String fundDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.id
     *
     * @return the value of flow_of_funds.id
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.id
     *
     * @param id the value for flow_of_funds.id
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.userId
     *
     * @return the value of flow_of_funds.userId
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.userId
     *
     * @param userId the value for flow_of_funds.userId
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.flowMoney
     *
     * @return the value of flow_of_funds.flowMoney
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getFlowMoney() {
        return flowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.flowMoney
     *
     * @param flowMoney the value for flow_of_funds.flowMoney
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setFlowMoney(BigDecimal flowMoney) {
        this.flowMoney = flowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.type
     *
     * @return the value of flow_of_funds.type
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.type
     *
     * @param type the value for flow_of_funds.type
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.source
     *
     * @return the value of flow_of_funds.source
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.source
     *
     * @param source the value for flow_of_funds.source
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.createTime
     *
     * @return the value of flow_of_funds.createTime
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.createTime
     *
     * @param createTime the value for flow_of_funds.createTime
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.fundDesc
     *
     * @return the value of flow_of_funds.fundDesc
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getFundDesc() {
        return fundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.fundDesc
     *
     * @param fundDesc the value for flow_of_funds.fundDesc
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setFundDesc(String fundDesc) {
        this.fundDesc = fundDesc;
    }
}