package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.Date;

public class FlowOfFunds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.userId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.flowMoney
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private BigDecimal flowmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.source
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.fundDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String funddesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.id
     *
     * @return the value of flow_of_funds.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.id
     *
     * @param id the value for flow_of_funds.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.userId
     *
     * @return the value of flow_of_funds.userId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.userId
     *
     * @param userid the value for flow_of_funds.userId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.flowMoney
     *
     * @return the value of flow_of_funds.flowMoney
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public BigDecimal getFlowmoney() {
        return flowmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.flowMoney
     *
     * @param flowmoney the value for flow_of_funds.flowMoney
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setFlowmoney(BigDecimal flowmoney) {
        this.flowmoney = flowmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.type
     *
     * @return the value of flow_of_funds.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.type
     *
     * @param type the value for flow_of_funds.type
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.source
     *
     * @return the value of flow_of_funds.source
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.source
     *
     * @param source the value for flow_of_funds.source
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.createTime
     *
     * @return the value of flow_of_funds.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.createTime
     *
     * @param createtime the value for flow_of_funds.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.fundDesc
     *
     * @return the value of flow_of_funds.fundDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getFunddesc() {
        return funddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.fundDesc
     *
     * @param funddesc the value for flow_of_funds.fundDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setFunddesc(String funddesc) {
        this.funddesc = funddesc;
    }
}