package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.Date;

public class FlowOfFunds {
    public FlowOfFunds() {
    }

    public FlowOfFunds(Integer id, Integer userId, BigDecimal flowMoney,
                       Integer type, String source, Date createTime, String fundDesc) {
        this.id = id;
        this.userId = userId;
        this.flowMoney = flowMoney;
        this.type = type;
        this.source = source;
        this.createTime = createTime;
        this.fundDesc = fundDesc;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.flowMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal flowMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.source
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_of_funds.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String fundDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.id
     *
     * @return the value of flow_of_funds.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.id
     *
     * @param id the value for flow_of_funds.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.userId
     *
     * @return the value of flow_of_funds.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.userId
     *
     * @param userId the value for flow_of_funds.userId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.flowMoney
     *
     * @return the value of flow_of_funds.flowMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getFlowMoney() {
        return flowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.flowMoney
     *
     * @param flowMoney the value for flow_of_funds.flowMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setFlowMoney(BigDecimal flowMoney) {
        this.flowMoney = flowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.type
     *
     * @return the value of flow_of_funds.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.type
     *
     * @param type the value for flow_of_funds.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.source
     *
     * @return the value of flow_of_funds.source
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.source
     *
     * @param source the value for flow_of_funds.source
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.createTime
     *
     * @return the value of flow_of_funds.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.createTime
     *
     * @param createTime the value for flow_of_funds.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_of_funds.fundDesc
     *
     * @return the value of flow_of_funds.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getFundDesc() {
        return fundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_of_funds.fundDesc
     *
     * @param fundDesc the value for flow_of_funds.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setFundDesc(String fundDesc) {
        this.fundDesc = fundDesc;
    }
}