package com.finance.pojo.others;

import java.math.BigDecimal;

public class FundProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.code
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String fundDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.dailyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal dailyGrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.monthlyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal monthlyGrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.annualGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal annualGrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal leastMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String invesTerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.id
     *
     * @return the value of fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.id
     *
     * @param id the value for fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.type
     *
     * @return the value of fund_product.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.type
     *
     * @param type the value for fund_product.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.code
     *
     * @return the value of fund_product.code
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.code
     *
     * @param code the value for fund_product.code
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.fundDesc
     *
     * @return the value of fund_product.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getFundDesc() {
        return fundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.fundDesc
     *
     * @param fundDesc the value for fund_product.fundDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setFundDesc(String fundDesc) {
        this.fundDesc = fundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.dailyGrowth
     *
     * @return the value of fund_product.dailyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getDailyGrowth() {
        return dailyGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.dailyGrowth
     *
     * @param dailyGrowth the value for fund_product.dailyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setDailyGrowth(BigDecimal dailyGrowth) {
        this.dailyGrowth = dailyGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.monthlyGrowth
     *
     * @return the value of fund_product.monthlyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getMonthlyGrowth() {
        return monthlyGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.monthlyGrowth
     *
     * @param monthlyGrowth the value for fund_product.monthlyGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setMonthlyGrowth(BigDecimal monthlyGrowth) {
        this.monthlyGrowth = monthlyGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.annualGrowth
     *
     * @return the value of fund_product.annualGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getAnnualGrowth() {
        return annualGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.annualGrowth
     *
     * @param annualGrowth the value for fund_product.annualGrowth
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAnnualGrowth(BigDecimal annualGrowth) {
        this.annualGrowth = annualGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.leastMoney
     *
     * @return the value of fund_product.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getLeastMoney() {
        return leastMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.leastMoney
     *
     * @param leastMoney the value for fund_product.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setLeastMoney(BigDecimal leastMoney) {
        this.leastMoney = leastMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.invesTerm
     *
     * @return the value of fund_product.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getInvesTerm() {
        return invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.invesTerm
     *
     * @param invesTerm the value for fund_product.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInvesTerm(String invesTerm) {
        this.invesTerm = invesTerm;
    }
}