package com.finance.pojo.others;

import java.math.BigDecimal;

public class FundProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.code
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.fundDesc
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String funddesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.dailyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal dailygrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.monthlyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal monthlygrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.annualGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal annualgrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal leastmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_product.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String investerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.id
     *
     * @return the value of fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.id
     *
     * @param id the value for fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.type
     *
     * @return the value of fund_product.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.type
     *
     * @param type the value for fund_product.type
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.code
     *
     * @return the value of fund_product.code
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.code
     *
     * @param code the value for fund_product.code
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.fundDesc
     *
     * @return the value of fund_product.fundDesc
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getFunddesc() {
        return funddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.fundDesc
     *
     * @param funddesc the value for fund_product.fundDesc
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setFunddesc(String funddesc) {
        this.funddesc = funddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.dailyGrowth
     *
     * @return the value of fund_product.dailyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getDailygrowth() {
        return dailygrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.dailyGrowth
     *
     * @param dailygrowth the value for fund_product.dailyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setDailygrowth(BigDecimal dailygrowth) {
        this.dailygrowth = dailygrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.monthlyGrowth
     *
     * @return the value of fund_product.monthlyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getMonthlygrowth() {
        return monthlygrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.monthlyGrowth
     *
     * @param monthlygrowth the value for fund_product.monthlyGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setMonthlygrowth(BigDecimal monthlygrowth) {
        this.monthlygrowth = monthlygrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.annualGrowth
     *
     * @return the value of fund_product.annualGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getAnnualgrowth() {
        return annualgrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.annualGrowth
     *
     * @param annualgrowth the value for fund_product.annualGrowth
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setAnnualgrowth(BigDecimal annualgrowth) {
        this.annualgrowth = annualgrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.leastMoney
     *
     * @return the value of fund_product.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getLeastmoney() {
        return leastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.leastMoney
     *
     * @param leastmoney the value for fund_product.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setLeastmoney(BigDecimal leastmoney) {
        this.leastmoney = leastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_product.invesTerm
     *
     * @return the value of fund_product.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getInvesterm() {
        return investerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_product.invesTerm
     *
     * @param investerm the value for fund_product.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setInvesterm(String investerm) {
        this.investerm = investerm;
    }
}