package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FundProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public FundProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Integer value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Integer value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Integer value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Integer value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Integer value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Integer> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Integer> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Integer value1, Integer value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andFundDescIsNull() {
            addCriterion("fundDesc is null");
            return (Criteria) this;
        }

        public Criteria andFundDescIsNotNull() {
            addCriterion("fundDesc is not null");
            return (Criteria) this;
        }

        public Criteria andFundDescEqualTo(String value) {
            addCriterion("fundDesc =", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescNotEqualTo(String value) {
            addCriterion("fundDesc <>", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescGreaterThan(String value) {
            addCriterion("fundDesc >", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescGreaterThanOrEqualTo(String value) {
            addCriterion("fundDesc >=", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescLessThan(String value) {
            addCriterion("fundDesc <", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescLessThanOrEqualTo(String value) {
            addCriterion("fundDesc <=", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescLike(String value) {
            addCriterion("fundDesc like", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescNotLike(String value) {
            addCriterion("fundDesc not like", value, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescIn(List<String> values) {
            addCriterion("fundDesc in", values, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescNotIn(List<String> values) {
            addCriterion("fundDesc not in", values, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescBetween(String value1, String value2) {
            addCriterion("fundDesc between", value1, value2, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andFundDescNotBetween(String value1, String value2) {
            addCriterion("fundDesc not between", value1, value2, "fundDesc");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthIsNull() {
            addCriterion("dailyGrowth is null");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthIsNotNull() {
            addCriterion("dailyGrowth is not null");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthEqualTo(BigDecimal value) {
            addCriterion("dailyGrowth =", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthNotEqualTo(BigDecimal value) {
            addCriterion("dailyGrowth <>", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthGreaterThan(BigDecimal value) {
            addCriterion("dailyGrowth >", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dailyGrowth >=", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthLessThan(BigDecimal value) {
            addCriterion("dailyGrowth <", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dailyGrowth <=", value, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthIn(List<BigDecimal> values) {
            addCriterion("dailyGrowth in", values, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthNotIn(List<BigDecimal> values) {
            addCriterion("dailyGrowth not in", values, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dailyGrowth between", value1, value2, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andDailyGrowthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dailyGrowth not between", value1, value2, "dailyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthIsNull() {
            addCriterion("monthlyGrowth is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthIsNotNull() {
            addCriterion("monthlyGrowth is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthEqualTo(BigDecimal value) {
            addCriterion("monthlyGrowth =", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthNotEqualTo(BigDecimal value) {
            addCriterion("monthlyGrowth <>", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthGreaterThan(BigDecimal value) {
            addCriterion("monthlyGrowth >", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("monthlyGrowth >=", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthLessThan(BigDecimal value) {
            addCriterion("monthlyGrowth <", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("monthlyGrowth <=", value, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthIn(List<BigDecimal> values) {
            addCriterion("monthlyGrowth in", values, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthNotIn(List<BigDecimal> values) {
            addCriterion("monthlyGrowth not in", values, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthlyGrowth between", value1, value2, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andMonthlyGrowthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthlyGrowth not between", value1, value2, "monthlyGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthIsNull() {
            addCriterion("annualGrowth is null");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthIsNotNull() {
            addCriterion("annualGrowth is not null");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthEqualTo(BigDecimal value) {
            addCriterion("annualGrowth =", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthNotEqualTo(BigDecimal value) {
            addCriterion("annualGrowth <>", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthGreaterThan(BigDecimal value) {
            addCriterion("annualGrowth >", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("annualGrowth >=", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthLessThan(BigDecimal value) {
            addCriterion("annualGrowth <", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("annualGrowth <=", value, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthIn(List<BigDecimal> values) {
            addCriterion("annualGrowth in", values, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthNotIn(List<BigDecimal> values) {
            addCriterion("annualGrowth not in", values, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("annualGrowth between", value1, value2, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andAnnualGrowthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("annualGrowth not between", value1, value2, "annualGrowth");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyIsNull() {
            addCriterion("leastMoney is null");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyIsNotNull() {
            addCriterion("leastMoney is not null");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyEqualTo(BigDecimal value) {
            addCriterion("leastMoney =", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyNotEqualTo(BigDecimal value) {
            addCriterion("leastMoney <>", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyGreaterThan(BigDecimal value) {
            addCriterion("leastMoney >", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("leastMoney >=", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyLessThan(BigDecimal value) {
            addCriterion("leastMoney <", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("leastMoney <=", value, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyIn(List<BigDecimal> values) {
            addCriterion("leastMoney in", values, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyNotIn(List<BigDecimal> values) {
            addCriterion("leastMoney not in", values, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leastMoney between", value1, value2, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andLeastMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leastMoney not between", value1, value2, "leastMoney");
            return (Criteria) this;
        }

        public Criteria andInvesTermIsNull() {
            addCriterion("invesTerm is null");
            return (Criteria) this;
        }

        public Criteria andInvesTermIsNotNull() {
            addCriterion("invesTerm is not null");
            return (Criteria) this;
        }

        public Criteria andInvesTermEqualTo(String value) {
            addCriterion("invesTerm =", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotEqualTo(String value) {
            addCriterion("invesTerm <>", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermGreaterThan(String value) {
            addCriterion("invesTerm >", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermGreaterThanOrEqualTo(String value) {
            addCriterion("invesTerm >=", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLessThan(String value) {
            addCriterion("invesTerm <", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLessThanOrEqualTo(String value) {
            addCriterion("invesTerm <=", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLike(String value) {
            addCriterion("invesTerm like", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotLike(String value) {
            addCriterion("invesTerm not like", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermIn(List<String> values) {
            addCriterion("invesTerm in", values, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotIn(List<String> values) {
            addCriterion("invesTerm not in", values, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermBetween(String value1, String value2) {
            addCriterion("invesTerm between", value1, value2, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotBetween(String value1, String value2) {
            addCriterion("invesTerm not between", value1, value2, "invesTerm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 15 08:54:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}