package com.finance.pojo.others;

import java.util.Date;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.sendId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer sendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.receiveId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer receiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.title
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.infoDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private String infodesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.status
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.sendId
     *
     * @return the value of info.sendId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.sendId
     *
     * @param sendid the value for info.sendId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.receiveId
     *
     * @return the value of info.receiveId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.receiveId
     *
     * @param receiveid the value for info.receiveId
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.createTime
     *
     * @return the value of info.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.createTime
     *
     * @param createtime the value for info.createTime
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.title
     *
     * @return the value of info.title
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.title
     *
     * @param title the value for info.title
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.infoDesc
     *
     * @return the value of info.infoDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public String getInfodesc() {
        return infodesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.infoDesc
     *
     * @param infodesc the value for info.infoDesc
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setInfodesc(String infodesc) {
        this.infodesc = infodesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.status
     *
     * @return the value of info.status
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.status
     *
     * @param status the value for info.status
     *
     * @mbggenerated Mon Jul 13 12:46:18 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}