package com.finance.pojo.others;

import com.finance.pojo.admin.Admin;

import java.util.Date;

public class Info {

    Admin admin;

    @Override
    public String toString() {
        return "Info{" +
                "admin=" + admin +
                ", id=" + id +
                ", sendId=" + sendId +
                ", receiveId=" + receiveId +
                ", createTime=" + createTime +
                ", title='" + title + '\'' +
                ", infoDesc='" + infoDesc + '\'' +
                ", status=" + status +
                '}';
    }

    public Admin getAdmin() {
        return admin;
    }

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.sendId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.receiveId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.infoDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String infoDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.status
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.sendId
     *
     * @return the value of info.sendId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.sendId
     *
     * @param sendId the value for info.sendId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setSendId(Integer sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.receiveId
     *
     * @return the value of info.receiveId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.receiveId
     *
     * @param receiveId the value for info.receiveId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setReceiveId(Integer receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.createTime
     *
     * @return the value of info.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.createTime
     *
     * @param createTime the value for info.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.title
     *
     * @return the value of info.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.title
     *
     * @param title the value for info.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.infoDesc
     *
     * @return the value of info.infoDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getInfoDesc() {
        return infoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.infoDesc
     *
     * @param infoDesc the value for info.infoDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInfoDesc(String infoDesc) {
        this.infoDesc = infoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.status
     *
     * @return the value of info.status
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.status
     *
     * @param status the value for info.status
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}