package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.Date;

public class Loan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.examineId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer examineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanTime
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Date loantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.amount
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.term
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.rate
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.applyStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer applystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer loanstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.id
     *
     * @return the value of loan.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.id
     *
     * @param id the value for loan.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanId
     *
     * @return the value of loan.loanId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanId
     *
     * @param loanid the value for loan.loanId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setLoanid(Integer loanid) {
        this.loanid = loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.examineId
     *
     * @return the value of loan.examineId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getExamineid() {
        return examineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.examineId
     *
     * @param examineid the value for loan.examineId
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setExamineid(Integer examineid) {
        this.examineid = examineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanTime
     *
     * @return the value of loan.loanTime
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Date getLoantime() {
        return loantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanTime
     *
     * @param loantime the value for loan.loanTime
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setLoantime(Date loantime) {
        this.loantime = loantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.amount
     *
     * @return the value of loan.amount
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.amount
     *
     * @param amount the value for loan.amount
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.term
     *
     * @return the value of loan.term
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.term
     *
     * @param term the value for loan.term
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.rate
     *
     * @return the value of loan.rate
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.rate
     *
     * @param rate the value for loan.rate
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.applyStatus
     *
     * @return the value of loan.applyStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getApplystatus() {
        return applystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.applyStatus
     *
     * @param applystatus the value for loan.applyStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setApplystatus(Integer applystatus) {
        this.applystatus = applystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanStatus
     *
     * @return the value of loan.loanStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getLoanstatus() {
        return loanstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanStatus
     *
     * @param loanstatus the value for loan.loanStatus
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setLoanstatus(Integer loanstatus) {
        this.loanstatus = loanstatus;
    }
}