package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.Date;

public class Loan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.examineId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer examineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Date loanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.amount
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.term
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.rate
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.applyStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer loanStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.id
     *
     * @return the value of loan.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.id
     *
     * @param id the value for loan.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanId
     *
     * @return the value of loan.loanId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanId
     *
     * @param loanId the value for loan.loanId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.examineId
     *
     * @return the value of loan.examineId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.examineId
     *
     * @param examineId the value for loan.examineId
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanTime
     *
     * @return the value of loan.loanTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Date getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanTime
     *
     * @param loanTime the value for loan.loanTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setLoanTime(Date loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.amount
     *
     * @return the value of loan.amount
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.amount
     *
     * @param amount the value for loan.amount
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.term
     *
     * @return the value of loan.term
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.term
     *
     * @param term the value for loan.term
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.rate
     *
     * @return the value of loan.rate
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.rate
     *
     * @param rate the value for loan.rate
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.applyStatus
     *
     * @return the value of loan.applyStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.applyStatus
     *
     * @param applyStatus the value for loan.applyStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setApplyStatus(Integer applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanStatus
     *
     * @return the value of loan.loanStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getLoanStatus() {
        return loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanStatus
     *
     * @param loanStatus the value for loan.loanStatus
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setLoanStatus(Integer loanStatus) {
        this.loanStatus = loanStatus;
    }
}