package com.finance.pojo.others;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String newsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsDesc
     *
     * @return the value of news.newsDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getNewsDesc() {
        return newsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsDesc
     *
     * @param newsDesc the value for news.newsDesc
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setNewsDesc(String newsDesc) {
        this.newsDesc = newsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.createTime
     *
     * @return the value of news.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.createTime
     *
     * @param createTime the value for news.createTime
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}