package com.finance.pojo.others;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class PayMoneyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public PayMoneyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyIsNull() {
            addCriterion("monthMoney is null");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyIsNotNull() {
            addCriterion("monthMoney is not null");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyEqualTo(BigDecimal value) {
            addCriterion("monthMoney =", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyNotEqualTo(BigDecimal value) {
            addCriterion("monthMoney <>", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyGreaterThan(BigDecimal value) {
            addCriterion("monthMoney >", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("monthMoney >=", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyLessThan(BigDecimal value) {
            addCriterion("monthMoney <", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("monthMoney <=", value, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyIn(List<BigDecimal> values) {
            addCriterion("monthMoney in", values, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyNotIn(List<BigDecimal> values) {
            addCriterion("monthMoney not in", values, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthMoney between", value1, value2, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andMonthMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthMoney not between", value1, value2, "monthMoney");
            return (Criteria) this;
        }

        public Criteria andAutoIntoIsNull() {
            addCriterion("autoInto is null");
            return (Criteria) this;
        }

        public Criteria andAutoIntoIsNotNull() {
            addCriterion("autoInto is not null");
            return (Criteria) this;
        }

        public Criteria andAutoIntoEqualTo(Integer value) {
            addCriterion("autoInto =", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoNotEqualTo(Integer value) {
            addCriterion("autoInto <>", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoGreaterThan(Integer value) {
            addCriterion("autoInto >", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoGreaterThanOrEqualTo(Integer value) {
            addCriterion("autoInto >=", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoLessThan(Integer value) {
            addCriterion("autoInto <", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoLessThanOrEqualTo(Integer value) {
            addCriterion("autoInto <=", value, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoIn(List<Integer> values) {
            addCriterion("autoInto in", values, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoNotIn(List<Integer> values) {
            addCriterion("autoInto not in", values, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoBetween(Integer value1, Integer value2) {
            addCriterion("autoInto between", value1, value2, "autoInto");
            return (Criteria) this;
        }

        public Criteria andAutoIntoNotBetween(Integer value1, Integer value2) {
            addCriterion("autoInto not between", value1, value2, "autoInto");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andInvesTermIsNull() {
            addCriterion("invesTerm is null");
            return (Criteria) this;
        }

        public Criteria andInvesTermIsNotNull() {
            addCriterion("invesTerm is not null");
            return (Criteria) this;
        }

        public Criteria andInvesTermEqualTo(String value) {
            addCriterion("invesTerm =", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotEqualTo(String value) {
            addCriterion("invesTerm <>", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermGreaterThan(String value) {
            addCriterion("invesTerm >", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermGreaterThanOrEqualTo(String value) {
            addCriterion("invesTerm >=", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLessThan(String value) {
            addCriterion("invesTerm <", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLessThanOrEqualTo(String value) {
            addCriterion("invesTerm <=", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermLike(String value) {
            addCriterion("invesTerm like", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotLike(String value) {
            addCriterion("invesTerm not like", value, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermIn(List<String> values) {
            addCriterion("invesTerm in", values, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotIn(List<String> values) {
            addCriterion("invesTerm not in", values, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermBetween(String value1, String value2) {
            addCriterion("invesTerm between", value1, value2, "invesTerm");
            return (Criteria) this;
        }

        public Criteria andInvesTermNotBetween(String value1, String value2) {
            addCriterion("invesTerm not between", value1, value2, "invesTerm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_money
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 15 08:54:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_money
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}