package com.finance.pojo.others;

import java.math.BigDecimal;

public class PayMoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_money.monthMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal monthMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_money.autoInto
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer autoInto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_money.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String invesTerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_money.id
     *
     * @return the value of pay_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_money.id
     *
     * @param id the value for pay_money.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_money.monthMoney
     *
     * @return the value of pay_money.monthMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getMonthMoney() {
        return monthMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_money.monthMoney
     *
     * @param monthMoney the value for pay_money.monthMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setMonthMoney(BigDecimal monthMoney) {
        this.monthMoney = monthMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_money.autoInto
     *
     * @return the value of pay_money.autoInto
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getAutoInto() {
        return autoInto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_money.autoInto
     *
     * @param autoInto the value for pay_money.autoInto
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAutoInto(Integer autoInto) {
        this.autoInto = autoInto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_money.type
     *
     * @return the value of pay_money.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_money.type
     *
     * @param type the value for pay_money.type
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_money.invesTerm
     *
     * @return the value of pay_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getInvesTerm() {
        return invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_money.invesTerm
     *
     * @param invesTerm the value for pay_money.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInvesTerm(String invesTerm) {
        this.invesTerm = invesTerm;
    }
}