package com.finance.pojo.others;

import java.math.BigDecimal;

public class TermFinancial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private String invesTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal leastMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.profit
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private Integer profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    private BigDecimal annualIncome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.id
     *
     * @return the value of term_financial.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.id
     *
     * @param id the value for term_financial.id
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.name
     *
     * @return the value of term_financial.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.name
     *
     * @param name the value for term_financial.name
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.invesTerm
     *
     * @return the value of term_financial.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public String getInvesTerm() {
        return invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.invesTerm
     *
     * @param invesTerm the value for term_financial.invesTerm
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setInvesTerm(String invesTerm) {
        this.invesTerm = invesTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.leastMoney
     *
     * @return the value of term_financial.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getLeastMoney() {
        return leastMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.leastMoney
     *
     * @param leastMoney the value for term_financial.leastMoney
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setLeastMoney(BigDecimal leastMoney) {
        this.leastMoney = leastMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.profit
     *
     * @return the value of term_financial.profit
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public Integer getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.profit
     *
     * @param profit the value for term_financial.profit
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setProfit(Integer profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.annualIncome
     *
     * @return the value of term_financial.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public BigDecimal getAnnualIncome() {
        return annualIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.annualIncome
     *
     * @param annualIncome the value for term_financial.annualIncome
     *
     * @mbggenerated Wed Jul 15 08:54:07 CST 2020
     */
    public void setAnnualIncome(BigDecimal annualIncome) {
        this.annualIncome = annualIncome;
    }
}