package com.finance.pojo.others;

import java.math.BigDecimal;

public class TermFinancial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.name
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private String investerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal leastmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.profit
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private Integer profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_financial.annualIncome
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    private BigDecimal annualincome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.id
     *
     * @return the value of term_financial.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.id
     *
     * @param id the value for term_financial.id
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.name
     *
     * @return the value of term_financial.name
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.name
     *
     * @param name the value for term_financial.name
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.invesTerm
     *
     * @return the value of term_financial.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public String getInvesterm() {
        return investerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.invesTerm
     *
     * @param investerm the value for term_financial.invesTerm
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setInvesterm(String investerm) {
        this.investerm = investerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.leastMoney
     *
     * @return the value of term_financial.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getLeastmoney() {
        return leastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.leastMoney
     *
     * @param leastmoney the value for term_financial.leastMoney
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setLeastmoney(BigDecimal leastmoney) {
        this.leastmoney = leastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.profit
     *
     * @return the value of term_financial.profit
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public Integer getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.profit
     *
     * @param profit the value for term_financial.profit
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setProfit(Integer profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_financial.annualIncome
     *
     * @return the value of term_financial.annualIncome
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public BigDecimal getAnnualincome() {
        return annualincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_financial.annualIncome
     *
     * @param annualincome the value for term_financial.annualIncome
     *
     * @mbggenerated Mon Jul 13 11:22:28 CST 2020
     */
    public void setAnnualincome(BigDecimal annualincome) {
        this.annualincome = annualincome;
    }
}