package com.finance.pojo.user;

import java.math.BigDecimal;
import java.util.Date;

public class UserFundProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.fundId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.startTime
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.averYield
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private BigDecimal averYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.profit
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.status
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.id
     *
     * @return the value of user_fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.id
     *
     * @param id the value for user_fund_product.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.userId
     *
     * @return the value of user_fund_product.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.userId
     *
     * @param userId the value for user_fund_product.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.fundId
     *
     * @return the value of user_fund_product.fundId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.fundId
     *
     * @param fundId the value for user_fund_product.fundId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setFundId(Integer fundId) {
        this.fundId = fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.startTime
     *
     * @return the value of user_fund_product.startTime
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.startTime
     *
     * @param startTime the value for user_fund_product.startTime
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.averYield
     *
     * @return the value of user_fund_product.averYield
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public BigDecimal getAverYield() {
        return averYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.averYield
     *
     * @param averYield the value for user_fund_product.averYield
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setAverYield(BigDecimal averYield) {
        this.averYield = averYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.profit
     *
     * @return the value of user_fund_product.profit
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.profit
     *
     * @param profit the value for user_fund_product.profit
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.status
     *
     * @return the value of user_fund_product.status
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.status
     *
     * @param status the value for user_fund_product.status
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}