package com.finance.pojo.user;

import java.math.BigDecimal;
import java.util.Date;

public class UserFundProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.userId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.fundId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private Integer fundid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.startTime
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.averYield
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private BigDecimal averyield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.profit
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fund_product.status
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.id
     *
     * @return the value of user_fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.id
     *
     * @param id the value for user_fund_product.id
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.userId
     *
     * @return the value of user_fund_product.userId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.userId
     *
     * @param userid the value for user_fund_product.userId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.fundId
     *
     * @return the value of user_fund_product.fundId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public Integer getFundid() {
        return fundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.fundId
     *
     * @param fundid the value for user_fund_product.fundId
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setFundid(Integer fundid) {
        this.fundid = fundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.startTime
     *
     * @return the value of user_fund_product.startTime
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.startTime
     *
     * @param starttime the value for user_fund_product.startTime
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.averYield
     *
     * @return the value of user_fund_product.averYield
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public BigDecimal getAveryield() {
        return averyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.averYield
     *
     * @param averyield the value for user_fund_product.averYield
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setAveryield(BigDecimal averyield) {
        this.averyield = averyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.profit
     *
     * @return the value of user_fund_product.profit
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.profit
     *
     * @param profit the value for user_fund_product.profit
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fund_product.status
     *
     * @return the value of user_fund_product.status
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fund_product.status
     *
     * @param status the value for user_fund_product.status
     *
     * @mbggenerated Mon Jul 13 11:22:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}