package com.finance.pojo.user;

public class UserPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.id
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.userId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.permissionId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.id
     *
     * @return the value of user_permissions.id
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.id
     *
     * @param id the value for user_permissions.id
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.userId
     *
     * @return the value of user_permissions.userId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.userId
     *
     * @param userid the value for user_permissions.userId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.permissionId
     *
     * @return the value of user_permissions.permissionId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.permissionId
     *
     * @param permissionid the value for user_permissions.permissionId
     *
     * @mbggenerated Mon Jul 13 12:47:28 CST 2020
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}