package com.finance.pojo.user;

import java.util.Date;

public class UserAvatar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.id
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.userId
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.avatar
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.create_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.last_use_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private Date last_use_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.status
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.id
     *
     * @return the value of user_avatar.id
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.id
     *
     * @param id the value for user_avatar.id
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.userId
     *
     * @return the value of user_avatar.userId
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.userId
     *
     * @param userId the value for user_avatar.userId
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.avatar
     *
     * @return the value of user_avatar.avatar
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.avatar
     *
     * @param avatar the value for user_avatar.avatar
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.create_time
     *
     * @return the value of user_avatar.create_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.create_time
     *
     * @param create_time the value for user_avatar.create_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.last_use_time
     *
     * @return the value of user_avatar.last_use_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public Date getLast_use_time() {
        return last_use_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.last_use_time
     *
     * @param last_use_time the value for user_avatar.last_use_time
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setLast_use_time(Date last_use_time) {
        this.last_use_time = last_use_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.status
     *
     * @return the value of user_avatar.status
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.status
     *
     * @param status the value for user_avatar.status
     *
     * @mbg.generated Wed Jul 22 09:11:19 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }
}