package com.finance.pojo.user;

public class UserPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permissions.permissionId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.id
     *
     * @return the value of user_permissions.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.id
     *
     * @param id the value for user_permissions.id
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.userId
     *
     * @return the value of user_permissions.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.userId
     *
     * @param userId the value for user_permissions.userId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permissions.permissionId
     *
     * @return the value of user_permissions.permissionId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permissions.permissionId
     *
     * @param permissionId the value for user_permissions.permissionId
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}