package com.finance.pojo.user;

import com.finance.pojo.others.PayMoney;

import java.math.BigDecimal;
import java.util.Date;

public class UserPayMoney {

    PayMoney payMoney;

    @Override
    public String toString() {
        return "UserPayMoney{" +
                "payMoney=" + payMoney +
                ", id=" + id +
                ", userId=" + userId +
                ", payId=" + payId +
                ", startTime=" + startTime +
                ", averYield=" + averYield +
                ", profit=" + profit +
                ", status=" + status +
                '}';
    }

    public PayMoney getPayMoney() {
        return payMoney;
    }

    public void setPayMoney(PayMoney payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.id
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.userId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.payId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private Integer payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.startTime
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.averYield
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private BigDecimal averYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.profit
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_money.status
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.id
     *
     * @return the value of user_pay_money.id
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.id
     *
     * @param id the value for user_pay_money.id
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.userId
     *
     * @return the value of user_pay_money.userId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.userId
     *
     * @param userId the value for user_pay_money.userId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.payId
     *
     * @return the value of user_pay_money.payId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.payId
     *
     * @param payId the value for user_pay_money.payId
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.startTime
     *
     * @return the value of user_pay_money.startTime
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.startTime
     *
     * @param startTime the value for user_pay_money.startTime
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.averYield
     *
     * @return the value of user_pay_money.averYield
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public BigDecimal getAverYield() {
        return averYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.averYield
     *
     * @param averYield the value for user_pay_money.averYield
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setAverYield(BigDecimal averYield) {
        this.averYield = averYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.profit
     *
     * @return the value of user_pay_money.profit
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.profit
     *
     * @param profit the value for user_pay_money.profit
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_money.status
     *
     * @return the value of user_pay_money.status
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_money.status
     *
     * @param status the value for user_pay_money.status
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}