package com.finance.pojo.others.task;

import java.util.Date;

public class AutoTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_task.id
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_task.name
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_task.invokeTime
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    private Date invokeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_task.type
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_task.targetStatus
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    private String targetStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_task.id
     *
     * @return the value of auto_task.id
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_task.id
     *
     * @param id the value for auto_task.id
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_task.name
     *
     * @return the value of auto_task.name
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_task.name
     *
     * @param name the value for auto_task.name
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_task.invokeTime
     *
     * @return the value of auto_task.invokeTime
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public Date getInvokeTime() {
        return invokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_task.invokeTime
     *
     * @param invokeTime the value for auto_task.invokeTime
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public void setInvokeTime(Date invokeTime) {
        this.invokeTime = invokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_task.type
     *
     * @return the value of auto_task.type
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_task.type
     *
     * @param type the value for auto_task.type
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_task.targetStatus
     *
     * @return the value of auto_task.targetStatus
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public String getTargetStatus() {
        return targetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_task.targetStatus
     *
     * @param targetStatus the value for auto_task.targetStatus
     *
     * @mbg.generated Mon Jul 20 13:13:58 CST 2020
     */
    public void setTargetStatus(String targetStatus) {
        this.targetStatus = targetStatus;
    }
}