package com.finance.mapper.user;

import com.finance.pojo.user.UserPayMoney;
import com.finance.pojo.user.UserPayMoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPayMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int countByExample(UserPayMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int deleteByExample(UserPayMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int insert(UserPayMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int insertSelective(UserPayMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    List<UserPayMoney> selectByExample(UserPayMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    UserPayMoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPayMoney record, @Param("example") UserPayMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int updateByExample(@Param("record") UserPayMoney record, @Param("example") UserPayMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int updateByPrimaryKeySelective(UserPayMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_money
     *
     * @mbggenerated Wed Jul 15 09:11:46 CST 2020
     */
    int updateByPrimaryKey(UserPayMoney record);
}