package com.finance.mapper.user;

import com.finance.pojo.user.UserFundProduct;
import com.finance.pojo.user.UserFundProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFundProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int countByExample(UserFundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int deleteByExample(UserFundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int insert(UserFundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int insertSelective(UserFundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    List<UserFundProduct> selectByExample(UserFundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    UserFundProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFundProduct record, @Param("example") UserFundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int updateByExample(@Param("record") UserFundProduct record, @Param("example") UserFundProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int updateByPrimaryKeySelective(UserFundProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fund_product
     *
     * @mbggenerated Wed Jul 15 08:52:12 CST 2020
     */
    int updateByPrimaryKey(UserFundProduct record);
}