package com.finance.mapper.user;

import com.finance.pojo.user.UserTermFinancial;
import com.finance.pojo.user.UserTermFinancialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTermFinancialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int countByExample(UserTermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int deleteByExample(UserTermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int insert(UserTermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int insertSelective(UserTermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    List<UserTermFinancial> selectByExample(UserTermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    UserTermFinancial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserTermFinancial record, @Param("example") UserTermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int updateByExample(@Param("record") UserTermFinancial record, @Param("example") UserTermFinancialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int updateByPrimaryKeySelective(UserTermFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_term_financial
     *
     * @mbggenerated Wed Jul 15 12:38:52 CST 2020
     */
    int updateByPrimaryKey(UserTermFinancial record);
}